### ISSUE TITLE
[Task]: Admin can create listing house rules

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-backend#104]
### Task Summary

Admin can create house rules for listing options

### Acceptance criteria

- [ ] Admin role can create house rules for listing options
- [ ] house rules can be publicly fetched for listing details options
- [ ] Admin role can update house rules

### Scenario

When user is creating listing, options should be available for user to add house rules for listing. House rules should be dynamic, letting user select from dynamic list. List should be populated by user.

### Any Additional Context

House rules should have descriptions, unique key value, and icon details
