### ISSUE TITLE
[Task]: Admin can create listing amenity options

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-backend#106]
### Task Summary

Admin should be able to manage listing amenity options

### Acceptance criteria

- [ ] Admin can create listing amenity options
- [ ] Amenity options can be publicly fetched
- [ ] Amenity options can be selected and associated with listings
- [ ] Depends on #105 

### Scenario

When user is creating listing, they should be able to select amenity options that appropriately describe features available on the listing

### Any Additional Context

Future Task: Amenity Requests should be available for options that might not be included on initial setup (Help us improve)
