### ISSUE TITLE
[Task]: Listings can have tags

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-backend#107]
### Task Summary

Users can add tags to listings

### Acceptance criteria

- [ ] Users can add tags to listings
- [ ] Tags are limited to 5 per listing
- [ ] Users should not be able to update tags
- [ ] To update tags, users need to send a support request

### Scenario

When a user is creating a listing, they can add tags to listings to make them more searchable.

### Any Additional Context

No other context
