### ISSUE TITLE
[Task]: Get User Followers

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-backend#109]
### Task Summary

Get User followers

### Acceptance criteria

- [ ] Get User followers
- [ ] results Should be paginated / infinitely scrollable
- [ ] Results should indicate if they follow logged in user
- [ ] Results should indicate if user follows them
- [ ] if logged in user is among results, should indicate that result item is self.

### Scenario

When a user visits a profile (not their own) and they navigate to the followers tab, or clicks the followers text in the profile details, they should see a list of the profiles' followers (if the users profile is public). If the users profile is private, then they can only see the profiles' followers if they are already following them.

### Any Additional Context

Any other context or additional information you wish to share about the proposed feature...
