### ISSUE TITLE
[Task]: User can create post with images

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-backend#111]
### Task Summary

A user can add images to a post when creating a post

### Acceptance criteria

- [ ] Logged in user can add images to post when uploading
- [ ] At least one image is required
- [ ] User can add maximum of 5 images

### Scenario

When a user is logged in, they can create a post to share content about anything. This post should have at least one image to showcase the content

### Any Additional Context

Future Task: 
- [ ] Post images should be reviewed for tos violations and moderation purposes
