### ISSUE TITLE
[Task]: Admin can create types or categories for personal ads

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-backend#144]
### Task Summary

Admin can create / update Types of personal ads

### Acceptance criteria

- [ ] Admin can create categories of personal ads
- [ ] Admin can update categories of personal ads
- [ ] Personal ad categories can be fetched publicly

### Scenario

When a logged in user wants to create a personal ad, since there are different types of ads possible, the user should be able to select the category of personal ads from a dynamically managed list of categories.

### Any Additional Context

No additional context necessary.
