### ISSUE TITLE
[Task]: Admin can crud Listing space types

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-backend#153]
### Task Summary

Admin can create update and delete listing space types

### Acceptance criteria

- [ ] Admin can create listing space type
- [ ] user can get active listing space types
- [ ] Admin can update listing space type
- [ ] Admin can delete listing space type
- [ ] Listing Types can only be deleted if they don't have any listings attached to them

### Scenario

When user is creating a listing, they can select a Listing Space Type to indicate how much space they would be offering to guests (e.g. Entire place, Private room, shared space etc.

### Any Additional Context

Be sure to provide extra context in type description
