### ISSUE TITLE
[Task]: Admin Analytics Summary

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-backend#178]
### Task Summary

Admin can view broad app metrics

### Acceptance criteria

- [ ] Admin can get number of users
- [ ] Admin can get number of published listings
- [ ] Admin can get number of published personal ads
- [ ] Admin can get number of published services

### Scenario

When admin navigates to admin dashboard, they can see a quick overview of how the app is doing (i.e. number of users, number of listings, number of services and number of personal ads
