### ISSUE TITLE
[Feat]: Tracking Sent Emails

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-backend#57]
### Feature Summary

When email is sent, record should be created and email tracked

### Acceptance criteria

- [ ] Record of sent email should be stored in database
- [ ] Record should be updated when email opened
- [ ] Endpoint to get Email tracking records
- [ ] Records should include names of templates used, user data, and time stamps

### Scenario

When Email is sent, and receiver opens it, we want to be able to confirm that.

### Any Additional Context

Future Task: Emails should use customizable templates that can be created and updated from a http client, and stored in db
