### ISSUE TITLE
[Task]: Chat service handle user login event

### ISSUE THREAD

**Issue by Bankole2000** [Bankole2000/cp-backend#91]
### Task Summary

Chat service handle user login event

### Acceptance criteria

- [ ] Check that user exists
- [ ] If user doesn't exist, create
- [ ] If first login create conversation with support
- [ ] Change user online status

### Scenario

When user logs in, and auth service emits user logged in event, other users in chat should see that user is online
If it's users first login, then user should receive welcome message from support account
